"""A map project: source (.map or Python generator) -> compiled, packaged, tested PK3.

Layout of ``maps/<name>/``::

    build.py        optional generator; defines ``build() -> MapBuilder | MapFile``
                    and optionally SHOTS (list of mohkit.game.Shot) and META (dict)
    <name>.map      hand-made source (used when there is no build.py)
    assets/         files copied verbatim into the PK3 (textures/, scripts/, sound/...)
    README.md

Outputs go to ``dist/<name>.pk3``, ``dist/<name>_shots.png`` and ``dist/<name>_report.json``;
intermediate files to the build dir (see mohkit.config).
"""

from __future__ import annotations

import importlib.util
import json
import time
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Sequence

from . import compile as _compile
from . import config as _config
from . import game as _game
from .mapfile import MapFile

REPO = _config.REPO
DIST = REPO / "dist"

DM_SCRIPT = """// {title}
// Generated by mohkit ({source})

main:

setcvar "g_obj_alliedtext1" "{title}"
setcvar "g_obj_alliedtext2" "{line2}"
setcvar "g_obj_alliedtext3" ""
setcvar "g_obj_axistext1" ""
setcvar "g_obj_axistext2" ""
setcvar "g_obj_axistext3" ""
setcvar "g_scoreboardpic" "{scoreboard}"

	if(level.roundbased)
		thread roundbasedthread

	level waittill prespawn

	exec global/DMprecache.scr
	level.script = maps/{path}.scr
	exec global/ambient.scr {ambience}
{extra}
	level waittill spawn

end

roundbasedthread:

	level waittill prespawn
	level waittill spawn

	level.dmrespawning = 0
	level.dmroundlimit = 5
	level.clockside = kills

	level waittill roundstart

end
"""


@dataclass
class Project:
    name: str                      # file name without extension, e.g. "dm_harbor"
    folder: Path
    mode: str = "dm"               # dm | obj
    title: str = ""
    ambience: str = "mohdm2"       # which stock map's music/ambience to reuse
    precache: list[str] = field(default_factory=list)
    script_extra: str = ""
    shots: list[_game.Shot] = field(default_factory=list)
    compile_args: dict = field(default_factory=dict)
    underlay: dict = field(default_factory=dict)   # reference overhead for the plan (render.underlay)

    @property
    def game_path(self) -> str:
        return f"{self.mode}/{self.name}"

    @classmethod
    def load(cls, folder: Path) -> "Project":
        folder = Path(folder).resolve()
        meta = {}
        gen = folder / "build.py"
        mod = None
        if gen.is_file():
            spec = importlib.util.spec_from_file_location(f"mohmap_{folder.name}", gen)
            assert spec and spec.loader
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            meta = dict(getattr(mod, "META", {}))
        p = cls(name=meta.get("name", folder.name), folder=folder, mode=meta.get("mode", "dm"),
                title=meta.get("title", folder.name), ambience=meta.get("ambience", "mohdm2"),
                precache=list(meta.get("precache", [])), script_extra=meta.get("script_extra", ""),
                compile_args=dict(meta.get("compile", {})), underlay=dict(meta.get("underlay", {})))
        p._module = mod  # type: ignore[attr-defined]
        if mod is not None:
            p.shots = list(getattr(mod, "SHOTS", []))
        return p

    # ------------------------------------------------------------------ steps
    def generate(self) -> MapFile:
        mod = getattr(self, "_module", None)
        if mod is not None and hasattr(mod, "build"):
            result = mod.build()
            m = result.to_map() if hasattr(result, "to_map") else result
            out = self.folder / f"{self.name}.map"
            m.save(str(out))
            return m
        src = self.folder / f"{self.name}.map"
        if not src.is_file():
            raise FileNotFoundError(f"{self.folder}: neither build.py nor {src.name}")
        return MapFile.load(str(src))

    def assets(self) -> dict[str, Path]:
        root = self.folder / "assets"
        if not root.is_dir():
            return {}
        return {str(p.relative_to(root)).replace("\\", "/"): p for p in sorted(root.rglob("*")) if p.is_file()}

    def scripts(self) -> dict[str, bytes]:
        path = self.game_path
        out = {}
        if not (self.folder / "assets" / "maps" / f"{path}.scr").exists():
            extra = self.script_extra
            out[f"maps/{path}.scr"] = DM_SCRIPT.format(
                title=self.title, line2="", scoreboard=self.name, path=path, ambience=self.ambience,
                extra=("\n" + extra + "\n") if extra else "", source=self.folder.name).encode("latin-1")
        if not (self.folder / "assets" / "maps" / f"{path}_precache.scr").exists():
            lines = ["exec global/DMprecache.scr"] + [f"cache {c}" for c in self.precache]
            out[f"maps/{path}_precache.scr"] = ("\n".join(lines) + "\n").encode("latin-1")
        return out

    def compile(self, m: MapFile, quality: str = "normal", **kw) -> _compile.CompileResult:
        args = dict(self.compile_args)
        args.update(kw)
        return _compile.compile_map(m.dumps(), self.game_path, assets=self.assets(), quality=quality, **args)

    def package(self, bsp: Path, out: Optional[Path] = None) -> Path:
        out = out or DIST / f"{self.name}.pk3"
        out.parent.mkdir(parents=True, exist_ok=True)
        files: dict[str, bytes] = {f"maps/{self.game_path}.bsp": Path(bsp).read_bytes()}
        files.update(self.scripts())
        for rel, p in self.assets().items():
            files[rel] = p.read_bytes()
        from .pak import unowned_paths
        shared = unowned_paths(files, self.name)
        if shared:
            # another installed map can ship the same path with other contents, and one
            # copy wins for every map (pak.path_clashes): keep assets under the map's name
            print(f"  ! {len(shared)} packaged files are not under the map's name '{self.name}'"
                  f" (another map's pk3 can replace them): {shared[:5]}")
        write_pk3(out, files)
        return out

    def test(self, pk3: Path, shots: Optional[Sequence[_game.Shot]] = None, **kw) -> _game.RunResult:
        return _game.run([pk3], self.game_path, list(shots if shots is not None else self.shots),
                         run_name=self.name, **kw)


def write_pk3(out: Path, files: dict[str, bytes]) -> None:
    """Deterministic PK3: sorted forward-slash names, fixed timestamps, deflate."""
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for name in sorted(files):
            info = zipfile.ZipInfo(name.replace("\\", "/"), date_time=(2001, 11, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            z.writestr(info, files[name])


def build(folder: Path, quality: str = "normal", test: bool = True, bots: int = 0, match_seconds: float = 0,
          log=print, inject_props: bool = True) -> dict:
    """Full pipeline for one project folder. Returns a report dict (also written to dist/).

    ``inject_props`` (default): compile without the ``static_*`` props (their collision
    ``.map`` brushes go into the world instead) and add them after the light stage,
    coloured from the map's lightmaps (``mohkit.staticlight``): no MOHlight static-model
    lighting, which runs on one thread at ~190 vertices a second (mk_medina's 107 props:
    ~55 minutes). On mk_medina the result matched MOHlight's props (docs/entities.md)."""
    t0 = time.time()
    proj = Project.load(folder)
    log(f"== {proj.game_path}: generating")
    m = proj.generate()
    from . import validate as _validate
    issues = _validate.check(m, _validate.load_shader_index())
    for i in issues:
        log(f"  {i}")
    if any(i.severity == "error" for i in issues):
        raise SystemExit(f"{proj.name}: validation errors, not compiling")
    statics: list = []
    read = None
    if inject_props:
        from . import config as _config, staticlight
        from .pak import GameFS
        fs = GameFS(_config.load().game_dir, loose=False)

        def _retail(path, _fs=fs):
            try:
                return _fs.read(path)
            except Exception:  # noqa: BLE001
                return None
        local = staticlight.files_reader(proj.assets())
        read = lambda p: local(p) or _retail(p)  # noqa: E731
        statics, clips = staticlight.take_statics(m, read)
        m.worldspawn.prims.extend(clips)
        log(f"== {len(statics)} static props held back for injection ({len(clips)} collision brushes)")
    log(f"== compiling ({quality})")
    res = proj.compile(m, quality=quality)
    log(res.summary())
    report = {"name": proj.name, "path": proj.game_path, "compile_ok": res.ok, "stats": res.stats,
              "problems": res.problems, "issues": [str(i) for i in issues]}
    if not res.ok:
        return report
    bsp = res.bsp
    if statics:
        from . import staticlight
        lit = DIST / f"{proj.name}.bsp"
        DIST.mkdir(parents=True, exist_ok=True)
        report["statics"] = staticlight.inject_statics(res.bsp, statics, read, lit)
        log(f"== static props injected: {report['statics']}")
        bsp = lit
    pk3 = proj.package(bsp)
    report["pk3"] = str(pk3)
    log(f"== packaged {pk3} ({pk3.stat().st_size // 1024} KB)")
    if test:
        run = proj.test(pk3, bots=bots, match_seconds=match_seconds)
        log(run.summary())
        report["run"] = {"screenshots": {k: str(v) for k, v in run.screenshots.items()},
                         "problems": run.problems, "kills": run.kills}
        if run.screenshots:
            DIST.mkdir(parents=True, exist_ok=True)
            sheet = _game.contact_sheet(run.screenshots, DIST / f"{proj.name}_shots.png")
            report["contact_sheet"] = str(sheet)
            log(f"== contact sheet {sheet}")
    report["seconds"] = round(time.time() - t0, 1)
    DIST.mkdir(parents=True, exist_ok=True)
    rp = DIST / f"{proj.name}_report.json"
    rp.write_text(json.dumps(report, indent=2))
    return report
