"""Minimal Source ``.mdl`` (studiohdr_t) header reader, versions 44-49 (CS:GO: 48/49).

Only metadata is read - no meshes. Offsets inside ``studiohdr_t`` (little endian)::

      0 int32  id "IDST"             4 int32 version       8 int32 checksum
     12 char   name[64]             76 int32 length (file size)
     80 float  eyeposition[3]       92 float illumposition[3]
    104 float  hull_min[3]         116 float hull_max[3]
    128 float  view_bbmin[3]       140 float view_bbmax[3]
    152 int32  flags
    156 int32  numbones, boneindex, numbonecontrollers, bonecontrollerindex,
               numhitboxsets, hitboxsetindex, numlocalanim, localanimindex,
               numlocalseq, localseqindex, activitylistversion, eventsindexed
    204 int32  numtextures         208 int32 textureindex       -> mstudiotexture_t[numtextures]
    212 int32  numcdtextures       216 int32 cdtextureindex     -> int32 string offsets
    220 int32  numskinref          224 int32 numskinfamilies    228 int32 skinindex -> int16 table
    232 int32  numbodyparts        236 int32 bodypartindex
    ...
    308 int32  surfacepropindex    (string offset from file start)
    312 int32  keyvalueindex       316 int32 keyvaluesize       (KeyValues text, e.g. prop_data)
    328 float  mass                332 int32 contents
    400 int32  studiohdr2index     (v46+: studiohdr2_t; sznameindex at +20 holds the long name)

``mstudiotexture_t`` is 64 bytes: ``int32 sznameindex`` (relative to the record),
``flags, used, unused1, material, clientmaterial, unused[10]``. The engine finds a
material by trying ``materials/<cdmaterial><texture name>.vmt`` for each
cdmaterials path in order.

``.vvd`` header: ``"IDSV", int32 version (4), checksum, numLODs, numLODVertexes[8],
numFixups, fixupTableStart, vertexDataStart, tangentDataStart`` - the LOD 0
vertex count is ``numLODVertexes[0]``.
"""

from __future__ import annotations

import os
import struct
from dataclasses import dataclass, field
from typing import Optional, Union

Vec3 = tuple[float, float, float]

STUDIOHDR_FLAGS = {
    0x1: "AUTOGENERATED_HITBOX", 0x2: "USES_ENV_CUBEMAP", 0x4: "FORCE_OPAQUE",
    0x8: "TRANSLUCENT_TWOPASS", 0x10: "STATIC_PROP", 0x20: "USES_FB_TEXTURE",
    0x40: "HASSHADOWLOD", 0x80: "USES_BUMPMAPPING", 0x100: "USE_SHADOWLOD_MATERIALS",
    0x200: "OBSOLETE", 0x400: "UNUSED", 0x800: "NO_FORCED_FADE", 0x1000: "FORCE_PHONEME_CROSSFADE",
    0x2000: "CONSTANT_DIRECTIONAL_LIGHT_DOT", 0x4000: "FLEXES_CONVERTED", 0x8000: "BUILT_IN_PREVIEW_MODE",
    0x10000: "AMBIENT_BOOST", 0x20000: "DO_NOT_CAST_SHADOWS", 0x40000: "CAST_TEXTURE_SHADOWS",
    0x200000: "VERT_ANIM_FIXED_POINT_SCALE",
}


def _cstr(data: bytes, offset: int, limit: int = 1024) -> str:
    if offset <= 0 or offset >= len(data):
        return ""
    end = data.find(b"\0", offset, offset + limit)
    if end < 0:
        end = min(len(data), offset + limit)
    return data[offset:end].decode("utf-8", "replace")


@dataclass
class MDLInfo:
    version: int
    checksum: int
    name: str
    length: int
    eyeposition: Vec3
    illumposition: Vec3
    hull_min: Vec3
    hull_max: Vec3
    view_bbmin: Vec3
    view_bbmax: Vec3
    flags: int
    num_bones: int
    num_skin_families: int
    num_skin_refs: int
    num_bodyparts: int
    materials: list[str]                 # texture/material names (mstudiotexture_t)
    cdmaterials: list[str]               # search directories, e.g. "models/props/de_dust/"
    skins: list[list[int]]               # [family][skinref] -> index into ``materials``
    surfaceprop: str
    keyvalues: str                       # raw KeyValues text ("prop_data" etc.), may be empty
    mass: float
    contents: int
    vvd_vertices: Optional[int] = None   # LOD0 vertex count if a .vvd was supplied
    flag_names: list[str] = field(default_factory=list)

    @property
    def is_static_prop(self) -> bool:
        return bool(self.flags & 0x10)

    def material_candidates(self, skin: int = 0) -> list[list[str]]:
        """For each material slot of ``skin``, the VMT names to try in cdmaterials order."""
        fam = self.skins[skin] if 0 <= skin < len(self.skins) else (self.skins[0] if self.skins else [])
        idx = fam if fam else list(range(len(self.materials)))
        out = []
        for i in idx:
            if not 0 <= i < len(self.materials):
                continue
            tex = self.materials[i].replace("\\", "/").lstrip("/")
            out.append([(cd.replace("\\", "/").strip("/") + "/" + tex).lstrip("/").lower() for cd in self.cdmaterials]
                       or [tex.lower()])
        return out

    def resolve_materials(self, source, skin: int = 0) -> list[Optional[str]]:
        """First existing ``materials/<cd><name>.vmt`` per slot (``None`` if missing)."""
        out: list[Optional[str]] = []
        for cands in self.material_candidates(skin):
            hit = None
            for c in cands:
                if source.try_read(f"materials/{c}.vmt") is not None:
                    hit = c
                    break
            out.append(hit)
        return out


class MDLError(ValueError):
    pass


def read_mdl(data: bytes, vvd: Optional[bytes] = None) -> MDLInfo:
    if len(data) < 408 or data[:4] != b"IDST":
        raise MDLError("not a Source MDL (IDST) file")
    version, checksum = struct.unpack_from("<ii", data, 4)
    if not 44 <= version <= 53:
        raise MDLError(f"unsupported MDL version {version}")
    name = data[12:76].split(b"\0", 1)[0].decode("utf-8", "replace")
    length = struct.unpack_from("<i", data, 76)[0]
    vecs = struct.unpack_from("<18f", data, 80)
    eye, illum, hmin, hmax, vmin, vmax = (tuple(vecs[i : i + 3]) for i in range(0, 18, 3))
    flags = struct.unpack_from("<i", data, 152)[0]
    num_bones = struct.unpack_from("<i", data, 156)[0]
    numtex, texidx, numcd, cdidx, nskinref, nfam, skinidx, nbody = struct.unpack_from("<8i", data, 204)

    materials = []
    for i in range(max(0, numtex)):
        rec = texidx + 64 * i
        name_ofs = struct.unpack_from("<i", data, rec)[0]
        materials.append(_cstr(data, rec + name_ofs))
    cdmaterials = []
    for i in range(max(0, numcd)):
        ofs = struct.unpack_from("<i", data, cdidx + 4 * i)[0]
        cdmaterials.append(_cstr(data, ofs))
    skins: list[list[int]] = []
    if nskinref > 0 and nfam > 0 and skinidx > 0:
        table = struct.unpack_from(f"<{nskinref * nfam}h", data, skinidx)
        skins = [list(table[f * nskinref : (f + 1) * nskinref]) for f in range(nfam)]

    surfaceprop = _cstr(data, struct.unpack_from("<i", data, 308)[0])
    kv_index, kv_size = struct.unpack_from("<ii", data, 312)
    keyvalues = ""
    if kv_index > 0 and kv_size > 0:
        keyvalues = data[kv_index : kv_index + kv_size].split(b"\0", 1)[0].decode("utf-8", "replace")
    mass, contents = struct.unpack_from("<fi", data, 328)

    if version >= 46:  # long name in studiohdr2_t when present
        hdr2 = struct.unpack_from("<i", data, 400)[0]
        if 0 < hdr2 < len(data) - 24:
            long_ofs = struct.unpack_from("<i", data, hdr2 + 20)[0]
            if long_ofs:
                long_name = _cstr(data, hdr2 + long_ofs)
                if long_name:
                    name = long_name

    info = MDLInfo(version, checksum, name, length, eye, illum, hmin, hmax, vmin, vmax, flags, num_bones, nfam,
                   nskinref, nbody, materials, cdmaterials, skins, surfaceprop, keyvalues, mass, contents,
                   flag_names=[n for bit, n in STUDIOHDR_FLAGS.items() if flags & bit])
    if vvd is not None:
        info.vvd_vertices = read_vvd_vertex_count(vvd)
    return info


def read_vvd_vertex_count(data: bytes) -> int:
    if data[:4] != b"IDSV":
        raise MDLError("not a VVD (IDSV) file")
    return struct.unpack_from("<i", data, 16)[0]  # numLODVertexes[0]


def load_mdl(source, path: str, with_vvd: bool = True) -> MDLInfo:
    """Read ``path`` (e.g. a static prop model name) from a VPK/SearchPath."""
    data = source.try_read(path)
    if data is None:
        raise KeyError(path)
    vvd = source.try_read(os.path.splitext(path)[0] + ".vvd") if with_vvd else None
    return read_mdl(data, vvd)


def open_mdl(path: Union[str, os.PathLike]) -> MDLInfo:
    with open(path, "rb") as fh:
        data = fh.read()
    vvd_path = os.path.splitext(str(path))[0] + ".vvd"
    vvd = open(vvd_path, "rb").read() if os.path.isfile(vvd_path) else None
    return read_mdl(data, vvd)
